# Arvore de Decisao

In [ ]:
#Importa as bibliotecas Pandas e Numpy
import pandas as pd
import numpy as np

In [ ]:
# na_values = substitui o valor '?' (dado faltante) para Nan
dataset = pd.read_csv('tic-tac-toe.data', sep=',',  index_col=0, na_values='?', names=['top-left-square','top-middle-square','top-right-squar','middle-left-square','middle-middle-square','middle-right-square','bottom-left-square','bottom-middle-square','bottom-right-square','end'])
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:
# elimina as linhas com dados faltantes
dataset = dataset.dropna(axis=0)
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:
#transforma dados categóricos em numericos
dataset = pd.get_dummies(dataset)
dataset

,end,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-squar_b,top-right-squar_o,top-right-squar_x,middle-left-square_b,middle-left-square_o,middle-left-square_x,...,middle-right-square_x,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x
top-left-square,,,,,,,,,,,,,,,,,,,,,
x,1,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
x,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
o,0,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,0,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,1,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
o,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [ ]:
#Separando as variáveis independentes (conjunto X) e a variável dependente y (que neste caso é a coluna 'end')
X = dataset.loc[:, dataset.columns != 'end'] 
y = np.array(dataset.loc[:, dataset.columns == 'end']).ravel()

In [ ]:
#Define os parametros do metodo de Arvore de Decisao
parameters= {'criterion':['gini'],'max_depth':[4,5,6,7,8,9,10,11,12,15,20,30,40,50,70,90,120,150], 'random_state': [56]}

In [ ]:
# importa o método do sklearn que separa em conjunto de treino e teste
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.26, stratify=y, random_state=56)

In [ ]:
# importa o GridSearchCV
from sklearn.model_selection import GridSearchCV
# importa a arvore de decisão
from sklearn.tree import DecisionTreeClassifier
# instancia o classificador 
clf = DecisionTreeClassifier()
gs_tree = GridSearchCV(clf,parameters, cv = 10, scoring = 'accuracy')
# o grid search treinará todos os modelos conforme a parametrização acima
gs_tree.fit(X,y)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini'],
                         'max_depth': [4, 5, 6, 7, 8, 9, 10, 11, 12, 15, 20, 30,
                                       40, 50, 70, 90, 120, 150],
                         'random_state': [56]},
             scoring='accuracy')

In [ ]:
# coloca os resultados num Frame para melhor visulização
results = pd.DataFrame(gs_tree.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_random_state,params,split0_test_score,split1_test_score,...,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004378,0.001049,0.002197,0.000629,gini,4,56,"{'criterion': 'gini', 'max_depth': 4, 'random_...",0.781250,0.833333,...,0.802083,0.770833,0.645833,0.645833,0.750000,0.915789,0.831579,0.750779,0.107124,17
1,0.003030,0.000065,0.001443,0.000028,gini,5,56,"{'criterion': 'gini', 'max_depth': 5, 'random_...",0.656250,0.812500,...,0.708333,0.791667,0.687500,0.625000,0.791667,0.873684,0.726316,0.727708,0.083422,18
2,0.003140,0.000075,0.001452,0.000048,gini,6,56,"{'criterion': 'gini', 'max_depth': 6, 'random_...",0.656250,0.843750,...,0.760417,0.812500,0.718750,0.697917,0.802083,0.894737,0.800000,0.769474,0.070276,3
3,0.003906,0.000822,0.001978,0.000806,gini,7,56,"{'criterion': 'gini', 'max_depth': 7, 'random_...",0.604167,0.791667,...,0.770833,0.781250,0.729167,0.708333,0.833333,0.947368,0.831579,0.767478,0.090222,4
4,0.003319,0.000073,0.001433,0.000023,gini,8,56,"{'criterion': 'gini', 'max_depth': 8, 'random_...",0.625000,0.781250,...,0.739583,0.750000,0.791667,0.697917,0.864583,0.978947,0.800000,0.775811,0.091092,1
5,0.003403,0.000068,0.001429,0.000013,gini,9,56,"{'criterion': 'gini', 'max_depth': 9, 'random_...",0.583333,0.729167,...,0.760417,0.781250,0.770833,0.708333,0.895833,0.947368,0.831579,0.771645,0.097670,2
6,0.003474,0.000089,0.001463,0.000081,gini,10,56,"{'criterion': 'gini', 'max_depth': 10, 'random...",0.593750,0.729167,...,0.739583,0.781250,0.760417,0.708333,0.885417,0.957895,0.789474,0.766404,0.094435,5
7,0.003644,0.000336,0.001593,0.000370,gini,11,56,"{'criterion': 'gini', 'max_depth': 11, 'random...",0.604167,0.718750,...,0.729167,0.760417,0.750000,0.708333,0.864583,0.957895,0.789474,0.759112,0.091289,15
8,0.003838,0.001028,0.001516,0.000255,gini,12,56,"{'criterion': 'gini', 'max_depth': 12, 'random...",0.593750,0.708333,...,0.729167,0.770833,0.739583,0.708333,0.854167,0.957895,0.800000,0.758081,0.092605,16
9,0.003611,0.000355,0.001459,0.000096,gini,15,56,"{'criterion': 'gini', 'max_depth': 15, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
10,0.004182,0.001040,0.001719,0.000430,gini,20,56,"{'criterion': 'gini', 'max_depth': 20, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
11,0.003668,0.000331,0.001507,0.000145,gini,30,56,"{'criterion': 'gini', 'max_depth': 30, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
12,0.003769,0.000487,0.001692,0.000292,gini,40,56,"{'criterion': 'gini', 'max_depth': 40, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
13,0.003496,0.000073,0.001447,0.000034,gini,50,56,"{'criterion': 'gini', 'max_depth': 50, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
14,0.003531,0.000139,0.001477,0.000099,gini,70,56,"{'criterion': 'gini', 'max_depth': 70, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
15,0.003576,0.000313,0.001497,0.000255,gini,90,56,"{'criterion': 'gini', 'max_depth': 90, 'random...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
16,0.004323,0.000982,0.001863,0.000549,gini,120,56,"{'criterion': 'gini', 'max_depth': 120, 'rando...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6
17,0.003992,0.000847,0.001752,0.000422,gini,150,56,"{'criterion': 'gini', 'max_depth': 150, 'rando...",0.583333,0.739583,...,0.750000,0.770833,0.739583,0.718750,0.875000,0.947368,0.800000,0.764320,0.092418,6

In [ ]:
#criar uma visão para facilitar a visualização dos resultados, e ordenar os resultados conforme os resultados.
view = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score']
results[view].sort_values(by='rank_test_score')

,params,mean_test_score,std_test_score,rank_test_score
4,"{'criterion': 'gini', 'max_depth': 8, 'random_...",0.775811,0.091092,1
5,"{'criterion': 'gini', 'max_depth': 9, 'random_...",0.771645,0.097670,2
2,"{'criterion': 'gini', 'max_depth': 6, 'random_...",0.769474,0.070276,3
3,"{'criterion': 'gini', 'max_depth': 7, 'random_...",0.767478,0.090222,4
6,"{'criterion': 'gini', 'max_depth': 10, 'random...",0.766404,0.094435,5
17,"{'criterion': 'gini', 'max_depth': 150, 'rando...",0.764320,0.092418,6
15,"{'criterion': 'gini', 'max_depth': 90, 'random...",0.764320,0.092418,6
16,"{'criterion': 'gini', 'max_depth': 120, 'rando...",0.764320,0.092418,6
9,"{'criterion': 'gini', 'max_depth': 15, 'random...",0.764320,0.092418,6
10,"{'criterion': 'gini', 'max_depth': 20, 'random...",0.764320,0.092418,6
11,"{'criterion': 'gini', 'max_depth': 30, 'random...",0.764320,0.092418,6
12,"{'criterion': 'gini', 'max_depth': 40, 'random...",0.764320,0.092418,6
13,"{'criterion': 'gini', 'max_depth': 50, 'random...",0.764320,0.092418,6
14,"{'criterion': 'gini', 'max_depth': 70, 'random...",0.764320,0.092418,6
7,"{'criterion': 'gini', 'max_depth': 11, 'random...",0.759112,0.091289,15
8,"{'criterion': 'gini', 'max_depth': 12, 'random...",0.758081,0.092605,16
0,"{'criterion': 'gini', 'max_depth': 4, 'random_...",0.750779,0.107124,17
1,"{'criterion': 'gini', 'max_depth': 5, 'random_...",0.727708,0.083422,18

# Multilayer-Perceptron (redes neurais)

In [ ]:
#Importa as bibliotecas Pandas e Numpy
import pandas as pd
import numpy as np

In [ ]:
# na_values = substitui o valor '?' (dado faltante) para Nan
dataset = pd.read_csv('tic-tac-toe.data', sep=',',  index_col=0, na_values='?',names=['top-left-square','top-middle-square','top-right-squar','middle-left-square','middle-middle-square','middle-right-square','bottom-left-square','bottom-middle-square','bottom-right-square','end'])
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:

# elimina as linhas com dados faltantes
dataset = dataset.dropna(axis=0)
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:
dataset = pd.get_dummies(dataset)
dataset

,end,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-squar_b,top-right-squar_o,top-right-squar_x,middle-left-square_b,middle-left-square_o,middle-left-square_x,...,middle-right-square_x,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x
top-left-square,,,,,,,,,,,,,,,,,,,,,
x,1,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
x,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
o,0,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,0,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,1,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
o,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [ ]:
#Separando as variáveis independentes (conjunto X) e a variável dependente y (que neste caso é a coluna 'end')
X = dataset.loc[:, dataset.columns != 'end'] 
y = np.array(dataset.loc[:, dataset.columns == 'end']).ravel()

In [ ]:
# importa o algoritmo de classificação Multilayer-Perceptron (redes neurais)
from sklearn.neural_network import MLPClassifier
# importa o GridSearchCV
from sklearn.model_selection import GridSearchCV

# na MLP um parâmetro a ser testado é a quantidade de neurônios na camada escondida, 
# onde utilzamos uma tupla para representar a camada escondida.
# Por exemplo:
# (5) - Cinco neurônios e uma camada escondida
# (8, 5) - Oito neurônios na primeira camada escondida e cinco neurônios na segunda camada escondida.
# Interessante nesse projeto utilizar no máximo duas camadas para verificação 
# Quanto mais camadas e neurônios maior o tempo de processamento do algoritmo
parameters = {'hidden_layer_sizes' : [(5), (8), (15), (5, 3), (8, 5), (10, 5)],
              'max_iter' : [3000], 'random_state' : [56]}

# define o algoritmo de classificação que será usado
mlp = MLPClassifier()
gs_mlp = GridSearchCV(mlp, parameters, cv=10, scoring='accuracy')
# o grid search treinará todos os modelos conforme a parametrização acima
gs_mlp.fit(X, y)

GridSearchCV(cv=10, estimator=MLPClassifier(),
             param_grid={'hidden_layer_sizes': [5, 8, 15, (5, 3), (8, 5),
                                                (10, 5)],
                         'max_iter': [3000], 'random_state': [56]},
             scoring='accuracy')

In [ ]:
#criar uma visão para facilitar a visualização dos resultados, e ordenar os resultados conforme os resultados.
view = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score']
results = pd.DataFrame(gs_mlp.cv_results_)
results[view].sort_values(by='rank_test_score')

,params,mean_test_score,std_test_score,rank_test_score
4,"{'hidden_layer_sizes': (8, 5), 'max_iter': 300...",0.783048,0.106004,1
5,"{'hidden_layer_sizes': (10, 5), 'max_iter': 30...",0.771612,0.108960,2
2,"{'hidden_layer_sizes': 15, 'max_iter': 3000, '...",0.754923,0.126590,3
3,"{'hidden_layer_sizes': (5, 3), 'max_iter': 300...",0.739167,0.083201,4
1,"{'hidden_layer_sizes': 8, 'max_iter': 3000, 'r...",0.738125,0.094299,5
0,"{'hidden_layer_sizes': 5, 'max_iter': 3000, 'r...",0.725603,0.098287,6

# Naive Bayes

In [ ]:
#Importa as bibliotecas Pandas e Numpy
import pandas as pd
import numpy as np

In [ ]:
# na_values = substitui o valor '?' (dado faltante) para Nan
dataset = pd.read_csv('tic-tac-toe.data', sep=',',  index_col=0, na_values='?', names=['top-left-square','top-middle-square','top-right-squar','middle-left-square','middle-middle-square','middle-right-square','bottom-left-square','bottom-middle-square','bottom-right-square','end'])
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:

# elimina as linhas com dados faltantes
dataset = dataset.dropna(axis=0)
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:
dataset = pd.get_dummies(dataset)
dataset

,end,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-squar_b,top-right-squar_o,top-right-squar_x,middle-left-square_b,middle-left-square_o,middle-left-square_x,...,middle-right-square_x,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x
top-left-square,,,,,,,,,,,,,,,,,,,,,
x,1,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
x,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
o,0,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,0,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,1,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
o,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [ ]:
#Separando as variáveis independentes (conjunto X) e a variável dependente y (que neste caso é a coluna 'end')
X = dataset.loc[:, dataset.columns != 'end'] 
y = np.array(dataset.loc[:, dataset.columns == 'end']).ravel()

In [ ]:
#Define os parametros do metodo Naive Bayes
param = {'var_smoothing': np.logspace(0,-9, num=100)}

In [ ]:
# importa o método do sklearn que separa em conjunto de treino e teste
from sklearn.model_selection import train_test_split
# importa o algoritmo Naive Bayes 
from sklearn.naive_bayes import GaussianNB
# importa o GridSearchCV
from sklearn.model_selection import GridSearchCV

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.45, random_state=56)
# instancia o classificador
gnb = GaussianNB()
gs_NB = GridSearchCV(gnb, param, cv = 10, scoring = 'accuracy')
# o grid search treinará todos os modelos conforme a parametrização acima
gs_NB.fit(X,y)

GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.3...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])},
             scoring='accuracy')

In [ ]:
#criar uma visão para facilitar a visualização dos resultados, e ordenar os resultados conforme os resultados.
view = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score']
results = pd.DataFrame(gs_NB.cv_results_)
results[view].sort_values(by='rank_test_score')

,params,mean_test_score,std_test_score,rank_test_score
0,{'var_smoothing': 1.0},0.681711,0.060651,1
1,{'var_smoothing': 0.8111308307896871},0.677544,0.069146,2
2,{'var_smoothing': 0.657933224657568},0.669178,0.070052,3
3,{'var_smoothing': 0.533669923120631},0.659803,0.072131,4
5,{'var_smoothing': 0.3511191734215131},0.657752,0.072839,5
...,...,...,...,...
43,{'var_smoothing': 0.0001232846739442066},0.638958,0.071115,22
42,{'var_smoothing': 0.0001519911082952933},0.638958,0.071115,22
41,{'var_smoothing': 0.0001873817422860383},0.638958,0.071115,22
59,{'var_smoothing': 4.328761281083053e-06},0.638958,0.071115,22
99,{'var_smoothing': 1e-09},0.638958,0.071115,22

# K Neighbors

In [ ]:
#Importa as bibliotecas Pandas e Numpy
import pandas as pd
import numpy as np

In [ ]:
# na_values = substitui o valor '?' (dado faltante) para Nan
dataset = pd.read_csv('tic-tac-toe.data', sep=',',  index_col=0, na_values='?', names=['top-left-square','top-middle-square','top-right-squar','middle-left-square','middle-middle-square','middle-right-square','bottom-left-square','bottom-middle-square','bottom-right-square','end'])
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:

# elimina as linhas com dados faltantes
dataset = dataset.dropna(axis=0)
dataset

,top-middle-square,top-right-squar,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square,end
top-left-square,,,,,,,,,
x,x,x,x,o,o,x,o,o,1
x,x,x,x,o,o,o,x,o,1
x,x,x,x,o,o,o,o,x,1
x,x,x,x,o,o,o,b,b,1
x,x,x,x,o,o,b,o,b,1
...,...,...,...,...,...,...,...,...,...
o,x,x,x,o,o,o,x,x,0
o,x,o,x,x,o,x,o,x,0
o,x,o,x,o,x,x,o,x,0
o,x,o,o,x,x,x,o,x,0
o,o,x,x,x,o,o,x,x,0

In [ ]:
dataset = pd.get_dummies(dataset)
dataset

,end,top-middle-square_b,top-middle-square_o,top-middle-square_x,top-right-squar_b,top-right-squar_o,top-right-squar_x,middle-left-square_b,middle-left-square_o,middle-left-square_x,...,middle-right-square_x,bottom-left-square_b,bottom-left-square_o,bottom-left-square_x,bottom-middle-square_b,bottom-middle-square_o,bottom-middle-square_x,bottom-right-square_b,bottom-right-square_o,bottom-right-square_x
top-left-square,,,,,,,,,,,,,,,,,,,,,
x,1,0,0,1,0,0,1,0,0,1,...,0,0,0,1,0,1,0,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,1,0
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
x,1,0,0,1,0,0,1,0,0,1,...,0,0,1,0,1,0,0,1,0,0
x,1,0,0,1,0,0,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
o,0,0,0,1,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,0,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,0,1,...,1,0,0,1,0,1,0,0,0,1
o,0,0,0,1,0,1,0,0,1,0,...,1,0,0,1,0,1,0,0,0,1
o,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,0,1,0,0,1

In [ ]:
#Separando as variáveis independentes (conjunto X) e a variável dependente y (que neste caso é a coluna 'end')
X = dataset.loc[:, dataset.columns != 'end'] 
y = np.array(dataset.loc[:, dataset.columns == 'end']).ravel()

In [ ]:
# importa o algoritmo de classifcaçaõ k-vizinhos
from sklearn.neighbors import KNeighborsClassifier
# importa o GridSearchCV
from sklearn.model_selection import GridSearchCV

# no grid coloca os hiperparâmetros do algoritmo que serão testados (dicionário)
# testará o valor de k com os seguintes valores e o hiperparâmetros weights com os valores 'uniform' e 'distance'
parameters = {'n_neighbors' : [1, 3, 5, 7, 9, 11, 13], 'weights' : ['uniform', 'distance']}

# define o algoritmo de classificação que será usado
knn = KNeighborsClassifier()
''' configura o GridSearch com o algoritmo de classificação = knn (instanciado), os parâmetros testados serão os 
    definidos em parameters, usa cross-validation = 10 e a medida de avaliação é a acurácia.'''  
gs = GridSearchCV(knn, parameters, cv=10, scoring='accuracy')
# o grid search treinará todos os modelos conforme a parametrização acima
gs.fit(X, y)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [ ]:
# coloca os resultados num Frame para melhor visulização
results = pd.DataFrame(gs.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,split5_test_score,split6_test_score,split7_test_score,split8_test_score,split9_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003193,0.000579,0.008394,0.001350,1,uniform,"{'n_neighbors': 1, 'weights': 'uniform'}",0.697917,0.729167,0.645833,0.781250,0.770833,0.739583,0.708333,0.697917,0.726316,0.652632,0.714978,0.042121,13
1,0.002895,0.000174,0.004663,0.001253,1,distance,"{'n_neighbors': 1, 'weights': 'distance'}",0.697917,0.729167,0.645833,0.781250,0.770833,0.739583,0.708333,0.697917,0.726316,0.652632,0.714978,0.042121,13
2,0.002842,0.000139,0.007963,0.000124,3,uniform,"{'n_neighbors': 3, 'weights': 'uniform'}",0.708333,0.822917,0.687500,0.739583,0.739583,0.729167,0.687500,0.770833,0.947368,0.768421,0.760121,0.073634,11
3,0.002807,0.000117,0.004426,0.000194,3,distance,"{'n_neighbors': 3, 'weights': 'distance'}",0.708333,0.822917,0.687500,0.739583,0.739583,0.729167,0.687500,0.770833,0.947368,0.768421,0.760121,0.073634,11
4,0.003243,0.000642,0.008768,0.000629,5,uniform,"{'n_neighbors': 5, 'weights': 'uniform'}",0.572917,0.729167,0.697917,0.729167,0.729167,0.760417,0.750000,0.885417,1.000000,0.873684,0.772785,0.112439,8
5,0.002885,0.000149,0.005672,0.001652,5,distance,"{'n_neighbors': 5, 'weights': 'distance'}",0.572917,0.729167,0.697917,0.729167,0.729167,0.760417,0.750000,0.885417,1.000000,0.873684,0.772785,0.112439,8
6,0.002883,0.000124,0.008464,0.000168,7,uniform,"{'n_neighbors': 7, 'weights': 'uniform'}",0.541667,0.750000,0.697917,0.708333,0.781250,0.802083,0.729167,0.864583,1.000000,0.873684,0.774868,0.116926,7
7,0.002949,0.000560,0.005997,0.003393,7,distance,"{'n_neighbors': 7, 'weights': 'distance'}",0.541667,0.739583,0.697917,0.708333,0.760417,0.802083,0.729167,0.875000,1.000000,0.873684,0.772785,0.118087,8
8,0.002781,0.000067,0.008666,0.000571,9,uniform,"{'n_neighbors': 9, 'weights': 'uniform'}",0.562500,0.781250,0.770833,0.708333,0.791667,0.781250,0.687500,0.864583,1.000000,0.863158,0.781107,0.111211,3
9,0.002765,0.000041,0.004849,0.000097,9,distance,"{'n_neighbors': 9, 'weights': 'distance'}",0.562500,0.760417,0.739583,0.708333,0.781250,0.781250,0.708333,0.885417,1.000000,0.863158,0.779024,0.112257,5
10,0.003417,0.001742,0.008472,0.000122,11,uniform,"{'n_neighbors': 11, 'weights': 'uniform'}",0.520833,0.781250,0.802083,0.760417,0.781250,0.760417,0.708333,0.843750,1.000000,0.863158,0.782149,0.115280,1
11,0.002979,0.000638,0.005637,0.001663,11,distance,"{'n_neighbors': 11, 'weights': 'distance'}",0.510417,0.770833,0.781250,0.760417,0.781250,0.760417,0.718750,0.864583,1.000000,0.863158,0.781107,0.118211,4
12,0.002811,0.000055,0.008608,0.000429,13,uniform,"{'n_neighbors': 13, 'weights': 'uniform'}",0.520833,0.781250,0.822917,0.718750,0.770833,0.781250,0.708333,0.791667,0.978947,0.894737,0.776952,0.114356,6
13,0.002765,0.000034,0.004900,0.000109,13,distance,"{'n_neighbors': 13, 'weights': 'distance'}",0.520833,0.791667,0.791667,0.718750,0.770833,0.781250,0.718750,0.822917,1.000000,0.894737,0.781140,0.117653,2

In [ ]:
#criar uma visão para facilitar a visualização dos resultados, e ordenar os resultados conforme os resultados.
view = ['params', 'mean_test_score', 'std_test_score', 'rank_test_score']
results[view].sort_values(by='rank_test_score')

,params,mean_test_score,std_test_score,rank_test_score
10,"{'n_neighbors': 11, 'weights': 'uniform'}",0.782149,0.115280,1
13,"{'n_neighbors': 13, 'weights': 'distance'}",0.781140,0.117653,2
8,"{'n_neighbors': 9, 'weights': 'uniform'}",0.781107,0.111211,3
11,"{'n_neighbors': 11, 'weights': 'distance'}",0.781107,0.118211,4
9,"{'n_neighbors': 9, 'weights': 'distance'}",0.779024,0.112257,5
12,"{'n_neighbors': 13, 'weights': 'uniform'}",0.776952,0.114356,6
6,"{'n_neighbors': 7, 'weights': 'uniform'}",0.774868,0.116926,7
4,"{'n_neighbors': 5, 'weights': 'uniform'}",0.772785,0.112439,8
5,"{'n_neighbors': 5, 'weights': 'distance'}",0.772785,0.112439,8
7,"{'n_neighbors': 7, 'weights': 'distance'}",0.772785,0.118087,8
2,"{'n_neighbors': 3, 'weights': 'uniform'}",0.760121,0.073634,11
3,"{'n_neighbors': 3, 'weights': 'distance'}",0.760121,0.073634,11
0,"{'n_neighbors': 1, 'weights': 'uniform'}",0.714978,0.042121,13
1,"{'n_neighbors': 1, 'weights': 'distance'}",0.714978,0.042121,13

# Calculo da Diferenca Absoluta

Observando os resultados, podemos ver que os metodos MLP e KNN tem as melhores performances, logo temos que calcular a diferenca absoluta para ver qual dos dois e de fato o melhor

In [ ]:
#Calculo do desvio padrao
import math
Dp = math.sqrt(((0.106004)*(0.106004) + (0.115280)*(0.115280))/2)
#Calculo da media
media = (0.783048 - 0.782149)
#calcula da Diferenca Absoluta
DA = media/Dp
print(DA)
#MLP > KNN

0.008118175535212203

Conclusao: O MLP tem uma melhor performance do que o KNN e o restante dos algoritmos